default:
  image: node:latest

stages:
  - setup
  - verify
  - deploy

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

install:
  stage: setup
  cache:
    paths:
      - .cache/npm
  script:
    - &npm_install
        npm ci --quiet --no-progress --cache=.cache/npm

lint:
  stage: verify
  cache: &pull_cache
    policy: pull
    paths:
      - .cache/npm
  script:
    - *npm_install
    - node_modules/.bin/gulp lint

bundle-dev:
  stage: deploy
  except:
    - main
  cache: *pull_cache
  script:
    - *npm_install
    - node_modules/.bin/gulp bundle
  artifacts:
    expire_in: 1 day # unless marked as keep from job page
    paths:
      - build/ui-bundle.zip

bundle-stable:
  stage: deploy
  only:
    - main@antora/antora-ui-default
  cache: *pull_cache
  script:
    - *npm_install
    - node_modules/.bin/gulp bundle
  artifacts:
    paths:
      - build/ui-bundle.zip

release:
  stage: deploy
  only:
    - main@antora/antora-ui-default
  cache: *pull_cache
  before_script:
    - *npm_install
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> .npmrc
  script:
    - npm run release

pages:
  stage: deploy
  only:
    - main@antora/antora-ui-default
  cache: *pull_cache
  script:
    - *npm_install
    - node_modules/.bin/gulp preview:build
    # FIXME figure out a way to avoid copying these files to preview site
    - rm -rf public/_/{helpers,layouts,partials}
  artifacts:
    paths:
      - public
