---

stages:
  - build

build:
  stage: build
  image: node:lts-slim
  tags:
    - docker
  script:
    - npm install
    - npx gulp bundle
  artifacts:
    expire_in: 1 day
    paths:
      - build/ui-bundle.zip
